import 'dart:io';
import 'package:tar/tar.dart';
import 'package:path_provider/path_provider.dart';

extension FileExtensions on File {
  /// Clears the model cache associated with this file on Android.
  /// This helps prevent "Cannot reserve space" crashes and other TFLite delegate issues.
  Future<void> clearModelCache(String modelFileName) async {
    if (!Platform.isAndroid) return;

    try {
      // Check in Documents directory (just in case)
      final docCacheFile = File('$path.xnnpack_cache');
      if (await docCacheFile.exists()) {
        await docCacheFile.delete();
      }

      // Check in Cache directory (where logs indicate it is)
      final tempDir = await getTemporaryDirectory();

      // List all files in temp directory
      final tempFiles = tempDir.listSync();

      // Delete any file that starts with the model file name
      // This covers .xnnpack_cache and .bin files generated by delegates
      for (var entity in tempFiles) {
        if (entity is File &&
            entity.path.split('/').last.startsWith(modelFileName)) {
          try {
            await entity.delete();
            print('Deleted cache file: ${entity.path}');
          } catch (e) {
            print('Failed to delete cache file ${entity.path}: $e');
          }
        }
      }
    } catch (e) {
      print('Error clearing model cache: $e');
    }
  }

  /// Extracts the Gemma model from a tar.gz archive.
  /// Returns true if the model file was found and extracted.
  Future<bool> extractGemmaModel(String targetDir, String modelFileName) async {
    // Open the file as a stream of bytes
    final fileStream = openRead();
    // Decompress using GZip
    final decompressedStream = fileStream.transform(gzip.decoder);
    // Read tar entries
    final reader = TarReader(decompressedStream);

    bool found = false;
    try {
      while (await reader.moveNext()) {
        final entry = reader.current;
        if (entry.type == TypeFlag.reg && entry.name.endsWith('.task')) {
          final taskFile = File('$targetDir/$modelFileName');
          // Pipe the entry content stream directly to the file
          await entry.contents.pipe(taskFile.openWrite());
          found = true;
          break; // Stop after finding the model
        }
      }
    } finally {
      await reader.cancel();
    }
    return found;
  }
}
